FL_36431865/Controllers/tRequestController.cs
using TicketManagement.Filtros;
using TicketManagement.Helpers;
using TicketManagement.Service;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace TicketManagement.Controllers
{
    [SessionExpire]
    public class tRequestController : Controller
    {
        private readonly log4net.ILog _Logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private readonly IBaseService _BaseService = new BaseService();

        // Requests
        public ActionResult Requests(string requestID, string requestTitle, string status, string situation)
        {
            try
            {
                // Parameters
                var list = new List<int>()
                {
                    Constants.Tables.RequestTypes,
                };
                var _ResultA = _BaseService.GetParametersByList(list);
                if (_ResultA.IsSuccess)
                {
                    ViewBag.ListOfRequestTypes = _ResultA.Data.FindAll(c => c.parameterID == Constants.Tables.RequestTypes);
                }
                else throw new Exception(_ResultA.Exception.Message);


                // Managers
                int roleID = 3;
                var _Result0A = _BaseService.GetUsersByRole(roleID);
                if (_Result0A.IsSuccess) ViewBag.ListOfManagers = _Result0A.Data;
                else throw new Exception(_Result0A.Exception.Message); 


                // Filters 
                int xrequestID = Functions.ToInt(requestID);
                string xrequestTitle = Functions.ToString(requestTitle);
                int xstatus = Functions.ToInt(status, 1);
                int xsituation = Functions.ToInt(situation, -1);

                var user = Functions.Deserialize<BLL.sUser>(Session["_USERDATA"].ToString());
                var data = new BLL.tRequest() { requestID = xrequestID, requestTitle = xrequestTitle, status = xstatus, situation = xsituation };
                var result = _BaseService.GetRequestsByFilter(xrequestID, xrequestTitle, xstatus, xsituation, user.userCode);
                if (result.IsSuccess)
                {
                    var output = new Model.Base<BLL.tRequest>()
                    {
                        Data = data,
                        Items = result.Data,
                    };
                    return View(output);
                }
                else throw new Exception(result.Exception.Message);
            }
            catch (Exception ex)
            {
                _Logger.Error(ex.Message, ex);
                TempData["Success"] = "0";
                TempData["Message"] = ex.Message;
                return View();
            }
        }

        // POST: tRequestController/Requests
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Requests(FormCollection collection)
        {
            try
            {
                // Parámeters
                var list = new List<int>()
                {
                    Constants.Tables.RequestTypes,
                };
                var _ResultA = _BaseService.GetParametersByList(list);
                if (_ResultA.IsSuccess)
                {
                    ViewBag.ListOfRequestTypes = _ResultA.Data.FindAll(c => c.parameterID == Constants.Tables.RequestTypes);
                }
                else throw new Exception(_ResultA.Exception.Message);


                // Managers
                int roleID = 3;
                var _Result0A = _BaseService.GetUsersByRole(roleID);
                if (_Result0A.IsSuccess) ViewBag.ListOfManagers = _Result0A.Data;
                else throw new Exception(_Result0A.Exception.Message); 


                //--------------------
                // Transaction Begin
                //-------------------- 
                int requestID = Functions.ToInt(collection["Data.requestID"]);
                string requestTitle = Functions.ToString(collection["Data.requestTitle"]);
                int status = Functions.ToInt(collection["Data.status"]);
                int situation = Functions.ToInt(collection["Data.situation"]);

                var user = Functions.Deserialize<BLL.sUser>(Session["_USERDATA"].ToString());
                var data = new BLL.tRequest() { requestID = requestID, requestTitle = requestTitle, status = status, situation = situation };
                var result = _BaseService.GetRequestsByFilter(requestID, requestTitle, status, situation, user.userCode);
                if (result.IsSuccess)
                {
                    var output = new Model.Base<BLL.tRequest>()
                    {
                        Data = data,
                        Items = result.Data,
                    };
                    return View(output);
                }
                else throw new Exception(result.Exception.Message);
            }
            catch (Exception ex)
            {
                _Logger.Error(ex.Message, ex);
                TempData["Success"] = "0";
                TempData["Message"] = ex.Message;
                return View();
            }
        }


        #region Web Methods

        // POST: GetRequestByID/
        [HttpPost]
        public ActionResult GetRequestByID(int requestID)
        {
            try
            {
                var result = _BaseService.GetRequestByID(requestID);
                if (result.IsSuccess)
                {
                    return Json(new { error = 0, message = "Request found", output = result.Data });
                }
                else throw new Exception(result.Exception.Message);
            }
            catch (Exception ex)
            {
                _Logger.Error(ex.Message, ex);
                return Json(new { error = 1, message = ex.Message });
            }
        }

        // POST: GetCommentsByRequestID/
        [HttpPost]
        public ActionResult GetCommentsByRequestID(int requestID)
        {
            try
            {
                var result = _BaseService.GetCommentsByRequestID(requestID);
                if (result.IsSuccess)
                {
                    return Json(new { error = 0, message = "Request found", output = result.Data });
                }
                else throw new Exception(result.Exception.Message);
            }
            catch (Exception ex)
            {
                _Logger.Error(ex.Message, ex);
                return Json(new { error = 1, message = ex.Message });
            }
        }

        // POST: CrateNewRequest/
        [HttpPost]
        public ActionResult CreateNewRequest(string requestTitle, string description, int requestType, string location)
        {
            try
            {
                var user = Functions.Deserialize<BLL.sUser>(Session["_USERDATA"].ToString()); 
                var xrequestTitle = Functions.ToString(requestTitle);
                var xdescription = Functions.ToString(description);
                var xrequestType = Functions.ToInt(requestType);
                var xlocation = Functions.ToString(location); 
                var result = _BaseService.CreateNewRequest(xrequestTitle, xdescription, xrequestType,xlocation, user.userCode);
                if (result.IsSuccess)
                {
                    TempData["Success"] = "1";
                    TempData["Message"] = "Record created";
                    return Json(new { error = 0, message = "Record created" });
                }
                else throw new Exception(result.Exception.Message);
            }
            catch (Exception ex)
            {
                _Logger.Error(ex.Message, ex);
                return Json(new { error = 1, message = ex.Message });
            }
        } 


        // POST: ReassignRequest/
        [HttpPost]
        public ActionResult ReassignRequest(int requestID, string assignedUser)
        {
            try
            {
                var user = Functions.Deserialize<BLL.sUser>(Session["_USERDATA"].ToString());
                var result = _BaseService.ReassignRequest(requestID, assignedUser, user.userCode);
                if (result.IsSuccess)
                {
                    TempData["Success"] = "1";
                    TempData["Message"] = "Record updated";
                    return Json(new { error = 0, message = "Record updated" });
                }
                else throw new Exception(result.Exception.Message);
            }
            catch (Exception ex)
            {
                _Logger.Error(ex.Message, ex);
                return Json(new { error = 1, message = ex.Message });
            }
        }

        // POST: ProcessRequest/
        [HttpPost]
        public ActionResult ProcessRequest(int requestID, int situation, string comments)
        {
            try
            {
                var user = Functions.Deserialize<BLL.sUser>(Session["_USERDATA"].ToString());
                var result = _BaseService.ProcessRequest(requestID, situation, comments, user.userCode);
                if (result.IsSuccess)
                {
                    TempData["Success"] = "1";
                    TempData["Message"] = "Record updated";
                    return Json(new { error = 0, message = "Record updated" });
                }
                else throw new Exception(result.Exception.Message);
            }
            catch (Exception ex)
            {
                _Logger.Error(ex.Message, ex);
                return Json(new { error = 1, message = ex.Message });
            }
        }

        // POST: CreateNewComment/
        [HttpPost]
        public ActionResult CreateNewComment(int requestID, string comment)
        {
            try
            {
                var user = Functions.Deserialize<BLL.sUser>(Session["_USERDATA"].ToString());
                var xcomment = Functions.ToString(comment); 

FL_36431865/Views/Users/Login.cshtml
@model TicketManagement.BLL.sUser

@{ Layout = ""; }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TicketManagement | Login</title>

    <!-- Bootstrap -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/lib/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="~/lib/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="~/Content/custom.min.css" rel="stylesheet">
    <link href="~/Content/toastr.min.css" rel="stylesheet">

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/custom.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>

    <script>

        $(function(){
            var message = '@TempData["Message"]';
            if (message != null && message != '') {
                var title = '@ViewBag.Title';
                var success = '@TempData["Success"]';
                if (success == "1") {
                    toastr.success(message, title);
                }
                else {
                    toastr.error(message, title);
                }
            }
        });

        $(document).ready(function () {
            var form = $('select[name="s"]').parent().parent();
            $(form).css("display", "none");
        });

        $(window).load(function () {
            $(".page-loader-variant-1").fadeOut(500);
        });


    </script>

    <script type="text/javascript">

        function Login() {
            var title = '@ViewBag.Title';
            var action = $('#action').val();
            var email = $('#txtemail').val();

            var message = '';
            if (email == '') message = message + "Enter your email" + "<br />";
            if (message != '') {
                toastr.error(message, title);
                return;
            }

            switch (action) {
                case "0":
                    var data = {};
                    data.email = email;
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("GetCredentialsByEmail")",
                        async: false,
                        data: data,
                        dataType: "json",
                        success: function (response) {
                            if (response.error == 0) {
                                var output = response.output;
                                if (output.action == "1") {
                                    $('#action').val("1");
                                    $('#btnLogin').text('Log in');
                                    $('#txtemail').attr('readonly', true);
                                    $('#divPassword').show();
                                    $('#divClientID').hide();
                                }
                                else {
                                    var data = output.data;
                                    $('#ddlclientID').empty();
                                    $.each(data, function (i, item) {
                                        $('#ddlclientID').append($('<option>', {
                                            value: item.clientID,
                                            text: item.clientName
                                        }));
                                    });

                                    $('#action').val("2");
                                    $('#btnLogin').text('Log in');
                                    $('#txtemail').attr('readonly', true);
                                    $('#divPassword').show();
                                    $('#divClientID').show();
                                }
                            }
                            else {
                                toastr.error(response.message, "");
                            }
                        },
                        failure: function (response) {
                            toastr.error(response, "");
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            toastr.error(XMLHttpRequest.responseText, "");
                        }
                    });

                    break;

                case "1":
                case "2":
                    debugger;
                    var password = $('#txtpassword').val();
                    if (password == '') {
                        toastr.error("Enter your password", title);
                        return;
                    }

                    var clientID = $('#ddlclientID').val();

                    var data = {};
                    data.email = email;
                    data.password = password;
                    data.clientID = clientID;
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("CheckLogin")",
                        async: false,
                        data: data,
                        dataType: "json",
                        success: function (response) {
                            debugger;
                            if (response.error == 0) {
                                window.location = "@Url.Action("Requests", "tRequest")";
                                @*window.location = "@Url.Action("Index", "Home")";*@
                            }
                            else {
                                toastr.error(response.message, "");
                            }
                        },
                        failure: function (response) {
                            toastr.error(response, "");
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            toastr.error(XMLHttpRequest.responseText, "");
                        }
                    });

                    break;
            }
        };
    </script>

    <style>
        .login_content h1:after, .login_content h1:before {
            height: 0px !important;
        }
    </style>

</head>

<body class="login">
    <form asp-action="Login">

        <div class="page-loader-variant-1">
            <div>
                <a class="brand brand-md brand-inverse" href="index.html">
                    @*<img src="../Images/LOGO2.png" alt="" width="182" height="45" />*@
                </a>
                <div class="page-loader-body">
                    <div id="spinningSquaresG">
                        <div class="spinningSquaresG" id="spinningSquaresG_1"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_2"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_3"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_4"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_5"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_6"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_7"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_8"></div>
                    </div>
                </div>
            </div>
        </div>

        <div>
            <a class="hiddenanchor" id="signup"></a>
            <a class="hiddenanchor" id="signin"></a>

            <div class="login_wrapper">
                <div class="animate form login_form">
                    <section class="login_content"> 

                        <h1>TicketManagement</h1>
                        <div class="form-group">
                            <input type="email" asp-for="email" id="txtemail" placeholder="User Email" class="form-control" MaxLength="200" />
                        </div>
                        <div class="form-group" id="divPassword" style="display:none">
                            <input type="password" asp-for="password" id="txtpassword" placeholder="Password" class="form-control" MaxLength="30" />
                        </div>
                        <div class="form-group" id="divClientID" style="display:none">
                            <select id="ddlclientID" class="form-control x-login-box"></select>
                        </div>
                        <div class="form-group">
                            <a id="btnLogin" class='btn btn-default submit' onclick='Login();' style='cursor:pointer;' href='javascript:;'>Continue</a>
                            <input type="hidden" id="action" value="0" />
                        </div>

                        <div class="clearfix"></div>

                        <div class="separator">
                            <p class="change_link">
                                New in the site?
                                <a href="/Users/Register" class="to_register">Create an account</a>
                            </p>

                            <div class="clearfix"></div>
                            <br />

                            <div>
                                <h4><i class="fa fa-home"></i> TicketManagement</h4>
                                <p>©@DateTime.Now.Year All right reserved</p>
                            </div>
                        </div> 
                    </section>
                </div>
            </div>
        </div>
    </form>
</body>

</html> 

FL_36431865/Views/Users/Register.cshtml
@model TicketManagement.BLL.sUser

@{
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TicketManagement | Login</title>

    <!-- Bootstrap -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/lib/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="~/lib/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="~/Content/custom.min.css" rel="stylesheet">
    <link href="~/Content/toastr.min.css" rel="stylesheet">

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/custom.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>

    <script>

        $(function () {
            var message = '@TempData["Message"]';
            if (message != null && message != '') {
                var title = '@ViewBag.Title';
                var success = '@TempData["Success"]';
                if (success == "1") {
                    toastr.success(message, title);
                }
                else {
                    toastr.error(message, title);
                }
            }
        });

        $(document).ready(function () {
            var form = $('select[name="s"]').parent().parent();
            $(form).css("display", "none");
        });

        $(window).load(function () {
            $(".page-loader-variant-1").fadeOut(500);
        });


    </script>

    <script type="text/javascript">

        function Login() {
            var title = '@ViewBag.Title';
            var action = $('#action').val();
            var email = $('#txtemail').val();
            var userName = $('#txtuserName').val();
            var password = $('#txtpassword').val();
            var passwordConfirmacion = $('#txtpasswordConfirmacion').val();

            var message = '';
            if (email == '') message = message + "Enter your email" + "<br />";
            if (userName == '') message = message + "Enter your user name" + "<br />";
            if (password == '') message = message + "Enter your password" + " < br /> ";
            if (passwordConfirmacion == '') message = message + "Enter your confirmation password" + " < br /> ";
            if (password.trim() != passwordConfirmacion.trim()) message = message + "The entered passwords are different" + " <br /> ";
            if (message != '')
            {
                toastr.error(message, title);
                return;
            }
            switch (action) {
                case "1":
                case "2":
                    debugger;

                    var clientID = $('#ddlclientID').val();

                    var data = {};
                    data.email = email;
                    data.userName = userName; // Add this line
                    data.password = password;
                    data.passwordConfirmacion = passwordConfirmacion;
                    data.clientID = clientID;
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("CreateAccount")",
                        async: false,
                        data: data,
                        dataType: "json",
                        success: function (response) {
                            debugger;
                            if (response.error == 0) {
                                window.location = "@Url.Action("Login", "Users")";
                                @*window.location = "@Url.Action("Index", "Home")";*@
                            }
                            else {
                                toastr.error(response.message, "");
                            }
                        },
                        failure: function (response) {
                            toastr.error(response, "");
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            toastr.error(XMLHttpRequest.responseText, "");
                        }
                    });

                    break;
            }
        };
    </script>

    <style>
        .login_content h1:after, .login_content h1:before {
            height: 0px !important;
        }
    </style>

</head>

<body class="login">
    <form asp-action="Register">

        <div class="page-loader-variant-1">
            <div>
                <a class="brand brand-md brand-inverse" href="index.html">
                    @*<img src="../Images/LOGO2.png" alt="" width="182" height="45" />*@
                </a>
                <div class="page-loader-body">
                    <div id="spinningSquaresG">
                        <div class="spinningSquaresG" id="spinningSquaresG_1"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_2"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_3"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_4"></div>
                      @*  <div class="spinningSquaresG" id="spinningSquaresG_5"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_6"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_7"></div>
                        <div class="spinningSquaresG" id="spinningSquaresG_8"></div>*@
                    </div>
                </div>
            </div>
        </div>

        <div>
            <a class="hiddenanchor" id="signup"></a>
            <a class="hiddenanchor" id="signin"></a>

            <div class="login_wrapper">

                <div id="register" class="animate form login_form">
                    <section class="login_content"> 
                        <h1>Create Account</h1>
                        <div class="form-group">
                            <input type="email" asp-for="email" id="txtemail" placeholder="User Email" class="form-control" MaxLength="200" />
                        </div>
                        <div class="form-group">
                            <input type="text" asp-for="userName" id="txtuserName" placeholder="User Name" class="form-control" MaxLength="200" />
                        </div>
                        <div class="form-group">
                            <input type="password" asp-for="password" id="txtpassword" placeholder="Password" class="form-control" MaxLength="30" />
                        </div>
                        <div class="form-group">
                            <input type="password" asp-for="passwordConfirmacion" id="txtpasswordConfirmacion" placeholder="Confirm Password" class="form-control" MaxLength="30" />
                        </div>
                        <div>
                            <a id="btnLogin" class='btn btn-default submit' onclick='Login();' style='cursor:pointer;' href='javascript:;'>Continue</a>
                            <input type="hidden" id="action" value="1" />
                        </div>

                        <div class="clearfix"></div>

                        <div class="separator">
                            <p class="change_link">
                                Already a member ?
                                <a href="/Users/Login" class="to_register">Log in</a>
                            </p>

                            <div class="clearfix"></div>
                            <br />

                            <div>
                                <h4><i class="fa fa-home"></i> TicketManagement</h4>
                                <p>©@DateTime.Now.Year All right reserved</p>
                            </div>
                        </div> 
                    </section>
                </div>
            </div>
        </div>
    </form>
</body>

</html> 